import { createHash } from 'node:crypto';
import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, extname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const output = join(root, 'build');
const legal = join(output, 'legal');
const digest = value => createHash('sha256').update(value).digest('hex');
const runtimeExtensions = new Set(['.html', '.css', '.js', '.mjs', '.wasm', '.glb', '.webp', '.svg']);

async function listFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async entry => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return listFiles(path);
    return entry.isFile() ? [path] : [];
  }));
  return files.flat().sort();
}

await stat(join(output, 'index.html'));
await mkdir(legal, { recursive: true });
await cp(join(root, 'licenses'), legal, { recursive: true });
await cp(join(root, 'LICENSE'), join(legal, 'LICENSE.txt'));

// Include exact application source, build inputs and notices with every published build.
// This archive is downloadable on demand and is deliberately outside the offline cache.
execFileSync('tar', [
  '-czf', join(legal, 'star-chess-party-source.tar.gz'),
  '--no-xattrs',
  ...(process.platform === 'darwin' ? ['--no-mac-metadata'] : []),
  '--exclude=.DS_Store', '--exclude=._*', '-C', root,
  'src', 'scripts', 'tests', 'public', 'licenses', '.github',
  'package.json', 'package-lock.json', 'vite.config.mjs', 'index.html', 'README.md', 'LICENSE',
], { stdio: 'inherit', env: { ...process.env, COPYFILE_DISABLE: '1' } });

// Keep source art in the archive above, then trim only this exact runtime list.
// Do not delete from public/ or use a broad glob: future runtime assets may differ.
const sourceOnlyArt = [
  'cloud-bot.png', 'cloud-stage-tall.png', 'cloud-stage-wide.png',
  'penguin.png', 'rabbit.png', 'team-sign.png', 'victory-crown.png',
  'background-manifest.json', 'character-manifest.json', 'props-manifest.json',
];
await Promise.all(sourceOnlyArt.map(name => rm(join(output, 'art', name), { force: true })));

const stockfish = JSON.parse(await readFile(join(legal, 'stockfish', 'manifest.json'), 'utf8'));
const archiveName = stockfish.source.archive.path.split('/').at(-1);
const networkName = stockfish.network.filename;
await writeFile(join(legal, 'index.html'), `<!doctype html>
<html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>星棋派对 · 源代码与许可</title>
<style>body{font:18px/1.7 system-ui,sans-serif;max-width:780px;margin:48px auto;padding:0 22px;color:#213d58}a{color:#13638b}li{margin:10px 0}code{overflow-wrap:anywhere}</style>
<h1>星棋派对：源代码与许可</h1>
<p>本项目自己的程序代码以 GNU GPL 第 3 版发布。第三方软件和图标保留各自的版权与许可声明。</p>
<ul>
<li><a href="LICENSE.txt">GNU GPL 第 3 版完整许可证</a></li>
<li><a href="star-chess-party-source.tar.gz">本次发布的完整应用源码与构建输入</a>：含 src、scripts、tests、public、licenses、依赖锁与发布配置。</li>
<li><a href="https://github.com/haowangggggg-lang/star-chess-party">项目 GitHub 仓库</a></li>
<li><a href="stockfish/${archiveName}">Stockfish.js 对应源码归档</a>，提交 <code>${stockfish.source.commit}</code>。</li>
<li><a href="stockfish/${networkName}">Stockfish Lite 的 NNUE 构建输入</a></li>
<li><a href="stockfish/README.md">Stockfish 来源、构建方法与验证边界</a> · <a href="stockfish/manifest.json">校验值</a> · <a href="stockfish/Copying.txt">许可证</a> · <a href="stockfish/AUTHORS">作者</a></li>
<li><a href="THREE-MIT.txt">Three.js MIT 许可</a> · <a href="CHESS-JS-BSD-2.txt">chess.js BSD-2-Clause 许可</a> · <a href="PHOSPHOR-MIT.txt">Phosphor 图标 MIT 许可</a></li>
</ul>
<p>美术原图与资产记录随应用源码包保留。本页和源码下载不加入游戏离线缓存，需要联网读取。</p>
<p><a href="../">返回棋盘</a></p></html>
`, 'utf8');

// Only immutable runtime resources enter the versioned cache. Source art remains
// in the downloadable source archive; other metadata and licenses stay network-only.
const resources = [];
for (const path of await listFiles(output)) {
  const name = relative(output, path).split('\\').join('/');
  if (name.startsWith('legal/') || name === 'sw.js' || !runtimeExtensions.has(extname(name))) continue;
  const bytes = await readFile(path);
  resources.push({ path: name, sha256: digest(bytes), bytes: bytes.byteLength });
}
if (!resources.some(entry => entry.path === 'index.html')) throw new Error('Missing runtime index.html');
const version = digest(Buffer.concat([
  await readFile(fileURLToPath(import.meta.url)), Buffer.from(JSON.stringify(resources)),
])).slice(0, 24);

const worker = `/* Generated by scripts/postbuild.mjs; never edit build/sw.js. */
'use strict';
const VERSION = ${JSON.stringify(version)};
const RESOURCES = ${JSON.stringify(resources, null, 2)};
const SCOPE = new URL(self.registration.scope);
const CACHE_PREFIX = 'star-chess-party:' + encodeURIComponent(SCOPE.href) + ':';
const CACHE_NAME = CACHE_PREFIX + VERSION;
const INDEX = new URL('index.html', SCOPE).href;
const ENTRIES = new Map(RESOURCES.map(entry => [new URL(entry.path, SCOPE).pathname, entry]));
const hex = buffer => Array.from(new Uint8Array(buffer), byte => byte.toString(16).padStart(2, '0')).join('');

async function fetchVerified(entry) {
  const url = new URL(entry.path, SCOPE).href;
  const response = await fetch(new Request(url, { cache: 'reload', credentials: 'same-origin', redirect: 'error' }));
  if (!response.ok || response.type === 'opaque') throw new Error('Resource unavailable: ' + entry.path);
  const bytes = await response.clone().arrayBuffer();
  const hash = hex(await crypto.subtle.digest('SHA-256', bytes));
  if (hash !== entry.sha256) throw new Error('Resource version mismatch: ' + entry.path);
  return response;
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    try {
      // A small bounded queue avoids a memory spike on mobile devices.
      let cursor = 0;
      const pending = await Promise.allSettled(Array.from({ length: Math.min(4, RESOURCES.length) }, async () => {
        while (cursor < RESOURCES.length) {
          const entry = RESOURCES[cursor++];
          await cache.put(new URL(entry.path, SCOPE).href, await fetchVerified(entry));
        }
      }));
      const failed = pending.find(result => result.status === 'rejected');
      if (failed) throw failed.reason;
    } catch (error) {
      await caches.delete(CACHE_NAME);
      throw error;
    }
    // No skipWaiting: an open game keeps its matching HTML, JS, WASM and models.
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
      .map(name => caches.delete(name)));
    // No clients.claim: never adopt an already-loaded page from a different build.
  })());
});

async function serveResource(entry) {
  const url = new URL(entry.path, SCOPE).href;
  let cache;
  try {
    cache = await caches.open(CACHE_NAME);
    const cached = await cache.match(url);
    if (cached) return cached;
  } catch {}
  try {
    // If storage was evicted, accept only the exact original content from the network.
    const response = await fetchVerified(entry);
    // A quota failure must not discard a valid online response. Installation
    // remains all-or-nothing; this is only best-effort repair after eviction.
    try { await cache?.put(url, response.clone()); } catch {}
    return response;
  } catch {
    return new Response('资源版本已更新或离线缓存不可用。请联网后关闭本游戏的全部页面，再重新打开。', {
      status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    });
  }
}

self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== SCOPE.origin || !url.pathname.startsWith(SCOPE.pathname)) return;
  const relative = url.pathname.slice(SCOPE.pathname.length);
  if (relative === 'legal' || relative.startsWith('legal/')) return;
  const entry = ENTRIES.get(url.pathname);
  if (entry) { event.respondWith(serveResource(entry)); return; }
  if (request.mode !== 'navigate') return;
  if (url.pathname === SCOPE.pathname) {
    event.respondWith(serveResource(ENTRIES.get(new URL(INDEX).pathname)));
    return;
  }
  // There are no client-side routes. Redirect an offline navigation to the real
  // index so relative asset paths keep working even from a nested URL.
  event.respondWith(fetch(request).catch(() => Response.redirect(INDEX, 302)));
});
`;
await writeFile(join(output, 'sw.js'), worker, 'utf8');
const bytes = resources.reduce((total, resource) => total + resource.bytes, 0);
console.log(`Postbuild: ${resources.length} runtime files, ${(bytes / 1024 / 1024).toFixed(2)} MiB, cache ${version}`);
console.log('Postbuild: source archives and notices are available at legal/index.html');
